CFLAGS = -Wall -fpic -coverage -lm
GCC = gcc
GCOV = gcov -b -c -f


#unittest1: dominion.o cards.o rngs.o unittest1.c interface.o
#	$(GCC) -o unittest1 unittest1.c dominion.o cards.o rngs.o interface.o $(CFLAGS)

#unittest2: unittest2.c dominion.o cards.o rngs.o interface.o
#	$(GCC) -o unittest2 unittest2.c dominion.o cards.o rngs.o interface.o $(CFLAGS)

#unittest3: unittest3.c dominion.o cards.o rngs.o
#	$(GCC) -o unittest3 unittest3.c dominion.o cards.o rngs.o $(CFLAGS)

#unittest4: unittest4.c dominion.o cards.o rngs.o interface.o
#	$(GCC) -o unittest4 unittest4.c dominion.o cards.o rngs.o interface.o $(CFLAGS)

#cardtest1: dominion.o cards.o rngs.o cardtest1.c interface.o
#	$(GCC) -o cardtest1 cardtest1.c dominion.o cards.o rngs.o interface.o $(CFLAGS)

#cardtest2: dominion.o cards.o rngs.o cardtest2.c interface.o
#	$(GCC) -o cardtest2 cardtest2.c dominion.o cards.o rngs.o interface.o $(CFLAGS)

#cardtest3: dominion.o cards.o rngs.o cardtest3.c interface.o
#	$(GCC) -o cardtest3 cardtest3.c dominion.o cards.o rngs.o interface.o $(CFLAGS)

#cardtest4: dominion.o cards.o rngs.o cardtest4.c interface.o
#	$(GCC) -o cardtest4 cardtest4.c dominion.o cards.o rngs.o interface.o $(CFLAGS)

#randomtestadventurer: dominion.o cards.o rngs.o randomtestadventurer.c
#	$(GCC) -o randomtestadventurer randomtestadventurer.c dominion.o cards.o rngs.o $(CFLAGS)

randomtestcard: dominion.o cards.o rngs.o randomtestcard.c
	$(GCC) -o randomtestcard randomtestcard.c dominion.o cards.o rngs.o $(CFLAGS)
