CFLAGS = -Wall -fpic -coverage -lm


#unittest1: unittest1.c dominion.o rngs.o interface.o
#	gcc -o unittest1 unittest1.c -g dominion.o rngs.o interface.o $(CFLAGS)
	
#unittest2: unittest2.c dominion.o rngs.o
#	gcc -o unittest2 unittest2.c -g dominion.o rngs.o $(CFLAGS)
	
#unittest3: unittest3.c dominion.o rngs.o
#	gcc -o unittest3 unittest3.c -g dominion.o rngs.o $(CFLAGS)
	
#unittest4: unittest4.c dominion.o rngs.o interface.o
#	gcc -o unittest4 unittest4.c -g dominion.o rngs.o interface.o $(CFLAGS)

#cardtest1: cardtest1.c dominion.o rngs.o interface.o
#	gcc -o cardtest1 cardtest1.c -g dominion.o rngs.o interface.o $(CFLAGS)
	
#cardtest2: cardtest2.c dominion.o rngs.o interface.o
#	gcc -o cardtest2 cardtest2.c -g dominion.o rngs.o interface.o $(CFLAGS)

#cardtest3: cardtest3.c dominion.o rngs.o interface.o
#	gcc -o cardtest3 cardtest3.c -g dominion.o rngs.o interface.o $(CFLAGS)
	
#cardtest4: cardtest4.c dominion.o rngs.o interface.o
#	gcc -o cardtest4 cardtest4.c -g dominion.o rngs.o interface.o $(CFLAGS)
	
#randomtestadventurer: randomtestadventurer.c dominion.o rngs.o
#	gcc -o randomtestadventurer randomtestadventurer.c -g dominion.o rngs.o $(CFLAGS)

randomtestcard: randomtestcard.c dominion.o rngs.o
	gcc -o randomtestcard randomtestcard.c -g dominion.o rngs.o $(CFLAGS)


	
	
	